docker-compose-yaml: docker-compose.yml

project: demo-fsa

tasks:
#   pre-rollout:
#     - run:
#         name: drush sql-dump
#         command: mkdir -p /app/web/sites/default/files/private/ && drush sql-dump --ordered-dump --gzip --result-file=/app/web/sites/default/files/private/pre-deploy-dump.sql.gz || true
#         service: cli

  post-rollout:
    - run:
        name: IF no Drupal installed and we are not main branch, sync from main brancy
        command: |
            if tables=$(drush sqlq 'show tables;') && [ -z "$tables" ] && [[ "$LAGOON_GIT_BRANCH" != "main" ]]; then
                # no drupal installed, sync DB from main branch
                drush -y sql-sync @lagoon.demo-fsa-main @self
                drush -y rsync @lagoon.demo-fsa-main:%files @self:%files
                drush -y cr
            fi
        service: cli
        shell: bash
#    - run:
#        name: drush cim
#        command: drush -y cim
#        service: cli
#    - run:
#        name: drush updb
#        command: drush -y updb
#        service: cli
#    - run:
#        name: drush cr
#        command: drush -y cr
#        service: cli

environments:
  main:
    routes:
      - nginx:
        - fsa.amazeeio.dev:
          tls-acme: 'false'
          insecure: Allow
    cronjobs:
      - name: drush cron
        schedule: "*/15 * * * *"
        command: drush cron
        service: cli
